[test-led]
Type        = "stairville/ledpar56-5ch"
Universe    = 1
Address     = 1
Count       = 2
Name        = "Test LED"
Groups      = ["test-led"]

[test-dimmer]
Type        = "generic/dimmer-1ch"
Universe    = 1
Address     = 250
Count       = 4
Name        = "Test Dimmer"
Groups      = ["test-dimmer"]
