Vendor  = "Stairville"
Model   = "LED Par56"
Mode    = "5ch"

URL     = "https://images.thomann.de/pics/atg/atgdata/document/manual/c_193245_en_online.pdf"

[[Channels]]
Control  = "mode"

[[Channels]]
Color    = "red"

[[Channels]]
Color    = "green"

[[Channels]]
Color    = "blue"

[[Channels]]
Control  = "speed"

[Colors.red]
Red     = 1.0

[Colors.green]
Green   = 1.0

[Colors.blue]
Blue    = 1.0

[Colors.cyan]
Green   = 1.0
Blue    = 1.0

[Colors.magenta]
Red     = 1.0
Blue    = 1.0

[Colors.amber]
Red     = 1.0
Green   = 0.5
